services:
  nacos:
    image: ${IMAGE_NACOS}
    restart: always
    environment:
      TZ: "Asia/Shanghai"
      PREFER_HOST_MODE: hostname
      # JAVA_OPT: "-Ddb.num=1 -Ddb.url.0=jdbc:postgresql://postgres:5432/nacos -Ddb.user.0=${POSTGRES_USER} -Ddb.password.0=${PASSWORD_POSTGRES}"
      # 必选：使用外置 数据库 模式
      MODE: standalone
      LOADER_PATH: /home/nacos/plugins
      SPRING_DATASOURCE_PLATFORM: postgresql
      DB_SERVICE_HOST: postgres
      DB_SERVICE_PORT: 5432
      DB_SERVICE_DB_NAME: nacos
      DB_SERVICE_USER: ${POSTGRES_USER}
      DB_SERVICE_PASSWORD: ${PASSWORD_POSTGRES}
      # pgsql连接参数已经设置，这里注释的是mysql的
      # DB_SERVICE_DB_PARAM: "characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true"
      # 可选：JVM 内存配置（根据服务器资源调整）
      JVM_XMS: 512m
      JVM_XMX: 512m
      JVM_XMN: 256m
      NACOS_AUTH_TOKEN: ${NACOS_AUTH_TOKEN}
      NACOS_AUTH_IDENTITY_KEY: nacos
      NACOS_AUTH_IDENTITY_VALUE: nacos
    volumes:
      - ${COSTRICT_DATA_DIR}/backend/nacos/logs:/home/nacos/logs
      - ${COSTRICT_DATA_DIR}/backend/nacos/data:/home/nacos/data
    ports:
      - "${PORT_NACOS}:8848"
      - "${PORT_NACOS_CONSOLE}:8080"
    networks:
      - shenma
