#!/bin/bash

#
# 功能：
#   gen-depend.sh 创建一个可以被 build-depends.sh 构建的依赖包定义文件（depends/<NAME>.json）。
#
#   它会依据 build-depends.sh 的读取/构建逻辑，生成一份合法的 JSON 定义。
#   只需提供 --name、--path 两个必填参数，其余字段（包括 version）会根据 name 与 type
#   自动推导出合理的默认值，最大程度减少必选项。
#
#   生成的 JSON 字段会被 build-depends.sh 按如下方式使用：
#     - name/version/repo/path/command/tag：渲染构建命令并执行构建
#     - type == "exec"：构建后导出镜像 tar 到 images/<name>/，并在 versions.json 中
#       记录 tag/file/platforms；其余类型仅记录 version
#     - update.workdir/command：使用 --update 时，在工作目录执行该命令以更新组件配置
#     - enabled：为 false 时，自动扫描 depends 目录构建时会被跳过
#
# 选项说明：
#   --name <NAME>                  模块名（必填）。同时决定输出文件名 depends/<NAME>.json
#   --path <PATH>                  构建镜像时的工作路径（必填）
#   --version <VERSION>            版本号（可选，默认：1.0.0）
#   --repo <REPO>                  Docker Hub 仓库名（默认：zgsm）
#   --type <TYPE>                  依赖类型：exec（默认）/ frontend
#   --tag <TAG>                    镜像标签模板（exec 默认：v{{.version}}，frontend 不输出）
#   --command <COMMAND>            构建命令模板（默认根据 type 自动生成）
#   --update-workdir <DIR>         组件更新工作目录（exec 默认：./configures/common/<NAME>）
#   --update-command <CMD>         组件更新命令（exec 默认：echo IMAGE_<ENV>=...）
#   --component-env-name <ENV>     image.env 中环境变量名（默认由 NAME 大写生成）
#   --no-update                    不生成 update 字段（frontend 默认即不生成）
#   --disabled                     将 enabled 置为 false
#   --description <DESC>           描述信息
#   --excludes <P1,P2,...>         排除文件列表（仅 frontend，默认排除 dist/.git/node_modules）
#   --force                        覆盖已存在的定义文件
#   -h, --help                     帮助信息
#
# 用法示例：
#   # 最简方式（其余字段自动推导）
#   ./gen-depend.sh --name my-service --version 1.0.0 --path ../../services/my-service
#
#   # 指定为禁用、自定义描述
#   ./gen-depend.sh --name my-service --version 1.0.0 --path ../../services/my-service \
#       --disabled --description "A demo service"
#
#   # 生成前端类型定义（不含 repo/tag/component，自动带 excludes）
#   ./gen-depend.sh --name my-frontend --version 1.0.0 --path ../../my-frontend --type frontend
#
#   # 覆盖环境变量名（如 one-api 对应 ONEAPI 而非 ONE_API）
#   ./gen-depend.sh --name one-api --version 1.0.4 --path ../../source/new-api \
#       --component-env-name ONEAPI
#

set -e

usage() {
    echo "Usage: gen-depend.sh [OPTIONS]"
    echo "Create a dependency definition JSON (depends/<NAME>.json) for build-depends.sh."
    echo ""
    echo "Required:"
    echo "  --name <NAME>                  Module name (also defines output filename)"
    echo "  --path <PATH>                  Build working path"
    echo ""
    echo "Optional (auto-derived when omitted):"
    echo "  --version <VERSION>            Version string (default: 1.0.0)"
    echo "  --repo <REPO>                  Docker hub repo (default: zgsm)"
    echo "  --type <TYPE>                  Dependency type: exec (default) / frontend"
    echo "  --tag <TAG>                    Image tag template (exec default: v{{.version}})"
    echo "  --command <COMMAND>            Build command template (auto-generated by type)"
    echo "  --update-workdir <DIR>         Component update workdir (exec default: ./configures/common/<NAME>)"
    echo "  --update-command <CMD>         Component update command (exec auto-generated)"
    echo "  --component-env-name <ENV>     Env var name in image.env (auto-generated from NAME)"
    echo "  --no-update                    Do not generate the 'update' field"
    echo "  --disabled                     Set enabled to false"
    echo "  --description <DESC>           Description"
    echo "  --excludes <P1,P2,...>         Exclude patterns (frontend default: dist/.git/node_modules)"
    echo "  --force                        Overwrite existing definition file"
    echo "  -h, --help                     Show this help"
    echo ""
    echo "Examples:"
    echo "  ./gen-depend.sh --name my-service --version 1.0.0 --path ../../services/my-service"
    echo "  ./gen-depend.sh --name my-frontend --version 1.0.0 --path ../../my-frontend --type frontend"
    exit 1
}

# 检查 jq 工具是否可用
if ! command -v jq >/dev/null 2>&1; then
    echo "Error: jq command not found! Please install jq to generate JSON files."
    exit 1
fi

# 默认参数
NAME=""
VERSION="1.0.0"
PATH_VALUE=""
REPO="zgsm"
TYPE="exec"
TAG=""
COMMAND=""
UPDATE_WORKDIR=""
UPDATE_COMMAND=""
NO_UPDATE=false
COMPONENT_ENV_NAME=""
ENABLED=""          # 空=不输出 enabled 字段；"false"=输出 enabled:false
DESCRIPTION=""
EXCLUDES=""
FORCE=false

# 解析命令行参数
while [ $# -gt 0 ]; do
    case "$1" in
        --name) NAME="$2"; shift 2;;
        --version) VERSION="$2"; shift 2;;
        --path) PATH_VALUE="$2"; shift 2;;
        --repo) REPO="$2"; shift 2;;
        --type) TYPE="$2"; shift 2;;
        --tag) TAG="$2"; shift 2;;
        --command) COMMAND="$2"; shift 2;;
        --update-workdir) UPDATE_WORKDIR="$2"; shift 2;;
        --update-command) UPDATE_COMMAND="$2"; shift 2;;
        --component-env-name) COMPONENT_ENV_NAME="$2"; shift 2;;
        --no-update) NO_UPDATE=true; shift;;
        --disabled) ENABLED="false"; shift;;
        --description) DESCRIPTION="$2"; shift 2;;
        --excludes) EXCLUDES="$2"; shift 2;;
        --force) FORCE=true; shift;;
        -h|--help) usage; exit 0;;
        *) echo "Unknown option: $1"; echo ""; usage;;
    esac
done

# 校验必填参数
if [ -z "$NAME" ]; then
    echo "Error: --name is required"
    echo ""
    usage
fi
if [ -z "$PATH_VALUE" ]; then
    echo "Error: --path is required"
    echo ""
    usage
fi

# 校验 type 取值
if [ "$TYPE" != "exec" ] && [ "$TYPE" != "frontend" ]; then
    echo "Error: --type must be 'exec' or 'frontend' (got: $TYPE)"
    echo ""
    usage
fi

# 由 NAME 生成 image.env 中的环境变量名后缀：连字符转下划线并大写
if [ -z "$COMPONENT_ENV_NAME" ]; then
    COMPONENT_ENV_NAME=$(echo "$NAME" | tr '[:lower:]-' '[:upper:]_')
fi

# ---- 根据类型推导默认值 ----

# 镜像标签：exec 默认 v{{.version}}；frontend 不需要 tag
if [ "$TYPE" = "exec" ] && [ -z "$TAG" ]; then
    TAG="v{{.version}}"
fi

# 构建命令：exec 默认 docker build；frontend 默认 bash build.sh
if [ -z "$COMMAND" ]; then
    if [ "$TYPE" = "exec" ]; then
        COMMAND="docker build --build-arg VERSION={{.version}} . -t {{.repo}}/{{.name}}:v{{.version}}"
    else
        COMMAND="bash build.sh"
    fi
fi

# 排除列表：frontend 默认排除 dist/.git/node_modules
if [ "$TYPE" = "frontend" ] && [ -z "$EXCLUDES" ]; then
    EXCLUDES="*/dist/*,*/.git/*,*/node_modules/*"
fi

# 决定是否生成 update 字段：
#   - --no-update 显式关闭
#   - exec 类型默认生成（除非被关闭）
#   - frontend 默认不生成，但若显式提供了 update-workdir/command 则生成
GENERATE_COMPONENT=true
if [ "$NO_UPDATE" = true ]; then
    GENERATE_COMPONENT=false
fi
if [ "$TYPE" = "frontend" ] && [ -z "$UPDATE_WORKDIR" ] && [ -z "$UPDATE_COMMAND" ]; then
    GENERATE_COMPONENT=false
fi
# 只要显式提供了 update-workdir 或 command，就强制生成
if [ -n "$UPDATE_WORKDIR" ] || [ -n "$UPDATE_COMMAND" ]; then
    GENERATE_COMPONENT=true
fi

# update 默认值（exec）
if [ "$GENERATE_COMPONENT" = true ]; then
    if [ -z "$UPDATE_WORKDIR" ]; then
        UPDATE_WORKDIR="./configures/common/${NAME}"
    fi
    if [ -z "$UPDATE_COMMAND" ]; then
        UPDATE_COMMAND="echo IMAGE_${COMPONENT_ENV_NAME}={{.repo}}/{{.name}}:v{{.version}} > ./image.env"
    fi
fi

# ---- 使用 jq 构建 JSON ----
# 策略：
#   1. 先在 shell 中预构建复杂值（component 对象、excludes 数组）的 JSON 片段；
#   2. 简单字符串字段用 --arg 传入，在 jq 过滤器中用 select(. != "") 剔除空值；
#   3. 非字符串字段（对象/数组/布尔）用 --argjson 传入，null 值会被 with_entries 剔除。
#   最终通过 with_entries(select(.value != null)) 保证输出整洁。

# frontend 类型不需要 repo 和 tag
if [ "$TYPE" = "frontend" ]; then
    REPO=""
    TAG=""
fi

# 预构建 update JSON 片段
if [ "$GENERATE_COMPONENT" = true ]; then
    COMPONENT_JSON=$(jq -nc \
        --arg workdir "$UPDATE_WORKDIR" \
        --arg command "$UPDATE_COMMAND" \
        '{workdir: $workdir, command: $command}')
else
    COMPONENT_JSON="null"
fi

# 预构建 excludes JSON 片段（JSON 数组或 null）
if [ -n "$EXCLUDES" ]; then
    EXCLUDES_JSON=$(echo "$EXCLUDES" | jq -Rsc 'split(",") | map(gsub("^\\s+|\\s+$";""))')
else
    EXCLUDES_JSON="null"
fi

# 组装最终 JSON（按 build-depends.sh 注释中的字段顺序）
RESULT=$(jq -n \
    --arg name "$NAME" \
    --arg repo "$REPO" \
    --arg version "$VERSION" \
    --arg type "$TYPE" \
    --arg path "$PATH_VALUE" \
    --arg command "$COMMAND" \
    --arg tag "$TAG" \
    --argjson update "$COMPONENT_JSON" \
    --arg enabled "$ENABLED" \
    --arg description "$DESCRIPTION" \
    --argjson excludes "$EXCLUDES_JSON" \
    '{
        name: $name,
        repo: (if $repo != "" then $repo else null end),
        version: $version,
        type: $type,
        path: $path,
        command: $command,
        tag: (if $tag != "" then $tag else null end),
        update: $update,
        enabled: (if $enabled == "false" then false else null end),
        description: (if $description != "" then $description else null end),
        excludes: $excludes
    } | with_entries(select(.value != null))')

# ---- 写入文件 ----
# depends 目录相对于脚本工作目录（与 build-depends.sh 保持一致）
DEPENDS_DIR="depends"
mkdir -p "$DEPENDS_DIR"

OUTPUT_FILE="${DEPENDS_DIR}/${NAME}.json"

if [ -f "$OUTPUT_FILE" ] && [ "$FORCE" != true ]; then
    echo "Error: Definition file already exists: $OUTPUT_FILE"
    echo "Use --force to overwrite."
    exit 1
fi

echo "$RESULT" > "$OUTPUT_FILE"

echo "Created dependency definition: $OUTPUT_FILE"
echo ""
echo "Generated content:"
echo "----------------------------------------------"
cat "$OUTPUT_FILE"
echo "----------------------------------------------"
echo ""
echo "You can now build it with:"
echo "  ./build-depends.sh -p ${NAME} --build"
echo "Or build + update component + push:"
echo "  ./build-depends.sh -p ${NAME} --build --update --push"
