services:
  costrict-web:
    image: ${IMAGE_COSTRICT_WEB}
    restart: always
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ${COSTRICT_DATA_DIR}/backend/costrict-web/logs:/app/logs
    networks:
      - shenma
