version: '3.8'

services:
  portal:
    image: nginx:latest
    restart: always
    environment:
      TZ: "Asia/Shanghai"
    volumes:
      - ../packages:/var/www/costrict
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80/tcp"
    networks:
      - shenma

networks:
  shenma:
    driver: bridge

