services:
  oneapi:
    image: ${IMAGE_ONEAPI}
    restart: always
    environment:
      TZ: "Asia/Shanghai"
    volumes:
      - /root/.costrict/data/oneapi/data:/data
    ports:
      - "${PORT_ONEAPI}:3000"
    networks:
      - shenma