services:
  client-manager:
    image: ${IMAGE_CLIENT_MANAGER}
    restart: always
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./config.yaml:/config/config.yaml:ro
      - ${COSTRICT_DATA_DIR}/backend/client-manager/data:/data
    networks:
      - shenma
