services:
  costrict-orgd:
    image: ${IMAGE_COSTRICT_ORGD}
    restart: always
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ${COSTRICT_DATA_DIR}/backend/costrict-orgd/logs:/app/logs
    networks:
      - shenma
