services:
  codebase-querier:
    image: ${IMAGE_CODEBASE_QUERIER}
    restart: always
    command: ["/app/server", "-f", "/app/conf/conf.yaml"]
    #ports:
    #  - "${PORT_CODEBASE_QUERIER}:8888"
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./conf.yaml:/app/conf/conf.yaml:ro
      - ${COSTRICT_DATA_DIR}/backend/codebase-querier/logs:/app/logs
    networks:
      - shenma
