services:
  costrict-admin-backend:
    image: ${IMAGE_COSTRICT_ADMIN_BACKEND}
    command: ["serve", "--console"]
    restart: always
    privileged: true
    pid: host
    volumes:
      - ./costrict-admin.json:/app/costrict-admin.json:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - ${COSTRICT_BACKEND_DIR}:${COSTRICT_BACKEND_DIR}
      - ${COSTRICT_DATA_DIR}:${COSTRICT_DATA_DIR}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      TZ: Asia/Shanghai
    networks:
      - shenma