services:
  authz:
    image: ${IMAGE_AUTHZ}
    restart: always
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./config.yaml:/app/config.yaml:ro
      - ${COSTRICT_DATA_DIR}/backend/authz/logs:/app/logs
    networks:
      - shenma
