services:
  costrict-auth-frontend:
    image: ${IMAGE_COSTRICT_AUTH_FRONTEND}
    restart: always
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ${COSTRICT_DATA_DIR}/backend/costrict-auth-frontend/logs:/app/logs
    networks:
      - shenma
