appname = casdoor
httpport = 8000
runmode = dev
copyrequestbody = true
SessionOn = true
driverName = postgres
dataSourceName = "user={{POSTGRES_USER}} password={{PASSWORD_POSTGRES}} host=postgres port=5432 dbname=casdoor sslmode=disable"
dbName=
redisEndpoint =
defaultStorageProvider =
isCloudIntranet = false
authState = "casdoor"
socks5Proxy = ""
verificationCodeTimeout = 10
initScore = 0
logPostOnly = true
origin = http://casdoor:8000
enableGzip = true
ldapServerPort = 10389
initDataNewOnly = false
