services:
  prometheus:
    image: ${IMAGE_PROMETHEUS}
    restart: always
    environment:
      TZ: "Asia/Shanghai"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "${PORT_PROMETHEUS}:9090"
    networks:
      - shenma

  grafana:
    image: ${IMAGE_GRAFANA}
    restart: always
    environment:
      TZ: "Asia/Shanghai"
    ports:
      - "${PORT_GRAFANA}:3000"
    volumes:
      - "./grafana/provisioning:/etc/grafana/provisioning"
      - "./grafana/dashboards:/var/lib/grafana/dashboards"
      - "./grafana/config/grafana.ini:/etc/grafana/grafana.ini:ro"
    networks:
      - shenma

  es:
    image: ${IMAGE_ES}
    environment:
      TZ: Asia/Shanghai
      discovery.type: single-node
      bootstrap.memory_lock: true
      xpack.security.enabled: false
      xpack.security.http.ssl.enabled: false  # Disable HTTPS
      xpack.ml.enabled: false
      ELASTIC_PASSWORD: "${PASSWORD_ELASTIC}"
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
    user: "1000:1000"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "${PORT_ES}:9200"
    volumes:
      - ${COSTRICT_DATA_DIR}/data/es/data:/usr/share/elasticsearch/data
    networks:
      - shenma