services:
  license-manager:
    image: ${IMAGE_LICENSE_MANAGER}
    restart: always
    environment:
      - SF_LICENSE_PRODUCT_KEY_NAME=GENERAL1
      - SF_LICENSE_FILE_PREFIX=/usr/local/platos/app/sf_license/licenses
      - TZ=Asia/Shanghai
    volumes:
      - ./scripts/startup.sh:/startup.sh:ro
      - ${COSTRICT_DATA_DIR}/backend/license-manager/logs:/usr/local/platos/app/sf_license/log
      - ${COSTRICT_DATA_DIR}/backend/license-manager/licenses:/usr/local/platos/app/sf_license/licenses
      - /etc/machine-id:/etc/machine-id:ro
    networks:
      - shenma
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:10000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
