services:
  costrict-model-proxy:
    image: ${IMAGE_COSTRICT_MODEL_PROXY}
    restart: always
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ${COSTRICT_DATA_DIR}/backend/costrict-model-proxy/logs:/app/logs
      - ./config.yaml:/app/config.yaml:ro
    networks:
      - shenma
