services:
  redis:
    image: ${IMAGE_REDIS}
    restart: always
    environment:
      TZ: "Asia/Shanghai"
    volumes:
      - /root/.costrict/data/redis/data:/data
    ports:
      - "${PORT_REDIS}:6379"
    networks:
      - shenma